
App:App.c add.o sub.o mul.o div.o
	gcc App.c add.c sub.c mul.c div.c -o App
	@echo "App is generated"

add.o:add.c 
	gcc -c add.c -o add.o
	@echo "add.o generated"

sub.o:sub.c
	gcc -c sub.c -o sub.o
	@echo "sub.o generated "	
mul.o:mul.c
	gcc -c mul.c -o mul.o
	@echo "mul.o is generated"

div.o:div.c
	gcc -c div.c -o div.o
	@echo "div.o is generated"


